# Generated by Django 4.1.1 on 2022-10-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='countries',
            new_name='country',
        ),
    ]
